# Generated by Django 4.2.4 on 2023-08-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_menu', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quatity',
        ),
        migrations.AlterField(
            model_name='order',
            name='dish_name',
            field=models.ManyToManyField(related_name='orders_as_dish', to='item_menu.dish'),
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_menu.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.ManyToManyField(related_name='orders_as_quantity', through='item_menu.OrderQuantity', to='item_menu.dish'),
        ),
    ]
