# Generated by Django 4.2.4 on 2023-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_menu', '0005_remove_order_quatity_alter_order_dish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='dish_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
