# Generated by Django 4.2.4 on 2023-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_menu', '0006_orderquantity_dish_name_alter_orderquantity_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-order_id'],
            },
        ),
    ]
